#!/bin/bash

cd /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/execution
tmpDir=$(mkdir -p "/Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/tmp.efc4781e" && echo "/Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/tmp.efc4781e")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/execution

)
(
cd /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/execution


kallisto quant -o Sample000Kallisto -i /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/inputs/-365897363/transcript_index /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/inputs/-780157667/reads_2.fastq.gz /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/inputs/-780157667/reads_2.fastq.gz
tar -zcvf Sample000Kallisto.quant.tar.gz Sample000Kallisto
)  > '/Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/execution/stdout' 2> '/Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/execution/stderr'
echo $? > /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/execution
find . -type d -empty -print0 | xargs -0 -I % touch %/.file
)
(
cd /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/execution
sync


)
mv /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/execution/rc.tmp /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-quant/execution/rc
