#!/bin/bash

cd /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-index/execution
tmpDir=$(mkdir -p "/Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-index/tmp.da47cc57" && echo "/Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-index/tmp.da47cc57")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-index/execution

)
(
cd /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-index/execution


kallisto index -i transcript_index /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-index/inputs/-780157667/transcripts.fasta.gz
)  > '/Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-index/execution/stdout' 2> '/Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-index/execution/stderr'
echo $? > /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-index/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-index/execution
find . -type d -empty -print0 | xargs -0 -I % touch %/.file
)
(
cd /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-index/execution
sync


)
mv /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-index/execution/rc.tmp /Users/tsang/git/2018-ACMBCB-workshop/ISB-CGC/cromwell-executions/kallisto/816921b3-54ee-467d-9b6b-9a5bf9cc3018/call-index/execution/rc
